### ISSUE TITLE
What to do with output once generated?

### ISSUE THREAD

**Issue by ericenns** [veg/hivtrace#6]
I have some scientists in my lab who have used hivtrace on the datamonkey server, but it has been down for at least a week now.

They would like to run it locally so I installed the application but It produces a json file which they do not now how to interpret.

Any ideas, is the js available for the datamonkey server.

**Comment by stevenweaver** [comment]
Hello ericenns, 

I'm sorry that you have experienced issues with using HIV-Trace. The application is still in testing, so unintended issues may be a bit more frequent than usual.

With that being said, the datamonkey server has been up the past week and I am able to run HIV Trace analyses with it. I believe a new feature released on September 2nd caused HIV Trace to break for you. The datamonkey server was using an irregular port for websockets which your firewall is probably blocking. I've updated the server to use port 80 for websockets, which should resolve that issue.

I have added a page [here](http://veg.github.io/hyphy-vision/hivtrace/) where you can upload your JSON file and visualize the results. Please let me know if either of these two options work for you. 

Regards,
Steven

**Comment by ericenns** [comment]
Hi Steven,

Thanks for the response, the datamonkey server is working for use as well as the page your linked.

I ended up creating a docker container for hivtrace which is found here ericenns/hivtrace-docker, and a simple web interface for hivtrace which I have called hivtrace-web found here ericenns/hivtrace-web.

This allows my scientists to run your application on their own local computer if they wish too.

**Comment by ericenns** [comment]
Hi Steven,

So the datamonkey server is still having issues with larger fasta files, for example 500 sequences.

It is appears to be an issue with the default nginx timeout values, so it can't get to the second screen before submission.

-Eric

**Comment by stevenweaver** [comment]
Hello Eric,

Thank you for providing a docker container and a small flask webapp. It's great to see this kind of enthusiasm. 

I've increased the default nginx timeout value. Please try again if you like. We are using a worker script to parse FASTA headers and infer attributes, and it looks as though that is taking quite some time in some cases. I'll see if I can find an alternative or supplemental solution to nginx timeout limits by the next release. 

- Steven

**Comment by stevenweaver** [comment]
Hello Eric,

I'm going to go ahead and close this issue. 
Please feel free to reopen if you continue to have issues with larger fasta files. 

Kind Regards,
Steven
